title: My First GitHub Pages Site # this is the part at the top
description: Built with Markdown, duct tape, and vibes # describe your site, the part at the bottom
theme: minima # you can ignore this unless you want to change your theme
